//
// Created by eddi on 23. 12. 8.
//

#ifndef GOGO_REQEUSTTOBOARDCONTROLLERFINDPOSTTOEDIT_H
#define GOGO_REQEUSTTOBOARDCONTROLLERFINDPOSTTOEDIT_H


class ReqeustToBoardControllerFindPostToEdit {

};


#endif //GOGO_REQEUSTTOBOARDCONTROLLERFINDPOSTTOEDIT_H
